# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhX3GvTbR0RgzfCyosC_edjUBGt0AEro
"""

# 1. Install the translation library
import ipywidgets as widgets
from deep_translator import GoogleTranslator
from IPython.display import display, clear_output

# Get a dictionary of all supported languages
langs_dict = GoogleTranslator().get_supported_languages(as_dict=True)
# Capitalize keys for better display
dropdown_options = {k.capitalize(): v for k, v in langs_dict.items()}

# 2. Create UI Elements
text_input = widgets.Textarea(
    placeholder='Type text here...',
    description='Text:',
    layout={'width': '90%', 'height': '100px'}
)

lang_dropdown = widgets.Dropdown(
    options=dropdown_options,
    value='es', # Default to Spanish
    description='Target:',
)

translate_button = widgets.Button(
    description='Translate Now',
    button_style='success', # 'success', 'info', 'warning', 'danger' or ''
    icon='check'
)

output_area = widgets.Output()

# 3. Define the translation logic
def on_button_clicked(b):
    with output_area:
        clear_output()
        text = text_input.value
        target_lang = lang_dropdown.value

        if text.strip() == "":
            print("Please enter some text first!")
            return

        try:
            translation = GoogleTranslator(source='auto', target=target_lang).translate(text)
            print("-" * 30)
            print(f"TRANSLATION:")
            print(translation)
            print("-" * 30)
        except Exception as e:
            print(f"An error occurred: {e}")

# 4. Connect button to the logic and display
translate_button.on_click(on_button_clicked)

print("--- ALL LANGUAGE TRANSLATOR ---")
display(text_input, lang_dropdown, translate_button, output_area)
